/**
 * Type-safe API Client for Custom Game Backend
 * 
 * This creates a dedicated axios instance for game backend API calls.
 * It uses OAuth SDK for authentication but maintains separation from SDK's internal requests.
 * 
 * Architecture:
 * - OAuth SDK's apiClient → Auth service (/api/oauth/*)
 * - GameAPI's axios → Game backend (/api/v1/*)
 * 
 * Features:
 * - Authorization header from OAuth SDK's getAccessToken()
 * - 401 token refresh & retry via OAuth SDK's refreshAccessToken()
 * - Type-safe business API methods
 * 
 * Note: 
 * - X-Client-Id: Optional (backend can extract from query param or header)
 * - X-Request-Id: Auto-generated by backend (Fastify)
 */

import { useOAuth } from '@autolabz/oauth-sdk';
import axios, { type AxiosInstance } from 'axios';
import type { 
  RoomInfo, 
  RolePerspective, 
  Action, 
  RoleMapping, 
} from './types';

/**
 * Game API: Type-safe wrapper around Axios instance
 */
export class GameAPI {
  constructor(private client: AxiosInstance) {}

  // ============ My Nexus APIs ============

  async getMyNexus(): Promise<RoomInfo> {
    const response = await this.client.get<RoomInfo>('/my-nexus');
    return response.data;
  }

  // ============ Room APIs ============

  async getRoomInfo(roomId: string): Promise<RoomInfo> {
    const response = await this.client.get<RoomInfo>(`/rooms/${roomId}`);
    return response.data;
  }

  async joinRoom(roomId: string, displayName: string): Promise<{ success: true; player_id: string; player: any }> {
    const response = await this.client.post(`/rooms/${roomId}/join`, { display_name: displayName });
    return response.data;
  }

  // ============ Owner Operations (Room-based) ============

  async selectGame(roomId: string, gameId: string): Promise<{ success: true; game_id: string }> {
    const response = await this.client.post(`/rooms/${roomId}/select-game`, { game_id: gameId });
    return response.data;
  }

  async addPlayer(roomId: string, player: {
    player_type: 'human' | 'llm';
    uid?: string;
    display_name: string;
    model_name?: string;
    system_prompt?: string;
  }): Promise<{ success: true; player_id: string; player: any }> {
    const response = await this.client.post(`/rooms/${roomId}/add-player`, player);
    return response.data;
  }

  async removePlayer(roomId: string, playerId: string): Promise<{ success: true }> {
    const response = await this.client.post(`/rooms/${roomId}/remove-player`, { player_id: playerId });
    return response.data;
  }

  async updateRoleMapping(roomId: string, roleMapping: RoleMapping, selectedPlayerCount?: number): Promise<{ success: true }> {
    const payload: { role_mapping: RoleMapping; selected_player_count?: number } = {
      role_mapping: roleMapping,
    };
    if (selectedPlayerCount !== undefined) {
      payload.selected_player_count = selectedPlayerCount;
    }
    const response = await this.client.post(`/rooms/${roomId}/update-role-mapping`, payload);
    return response.data;
  }

  async startGame(roomId: string, roleMapping: RoleMapping, selectedPlayerCount?: number): Promise<{ success: true }> {
    const payload: { role_mapping: RoleMapping; selected_player_count?: number } = {
      role_mapping: roleMapping,
    };
    if (selectedPlayerCount !== undefined) {
      payload.selected_player_count = selectedPlayerCount;
    }
    const response = await this.client.post(`/rooms/${roomId}/start`, payload);
    return response.data;
  }

  async pauseGame(roomId: string): Promise<{ success: true }> {
    const response = await this.client.post(`/rooms/${roomId}/pause`);
    return response.data;
  }

  async resumeGame(roomId: string): Promise<{ success: true }> {
    const response = await this.client.post(`/rooms/${roomId}/resume`);
    return response.data;
  }

  async stopGame(roomId: string): Promise<{ success: true }> {
    const response = await this.client.post(`/rooms/${roomId}/stop`);
    return response.data;
  }

  async restartGame(roomId: string): Promise<{ success: true }> {
    const response = await this.client.post(`/rooms/${roomId}/restart`);
    return response.data;
  }

  // ============ Action APIs ============

  async submitAction(roomId: string, action: Action): Promise<{ success: true; message: string }> {
    const response = await this.client.post(`/rooms/${roomId}/actions`, action);
    return response.data;
  }

  // ============ Perspective APIs ============

  async getPerspective(roomId: string, roleId: string): Promise<RolePerspective> {
    const response = await this.client.get<RolePerspective>(
      `/rooms/${roomId}/perspectives/${roleId}`
    );
    return response.data;
  }
}

/**
 * Hook: Get game API client
 * 
 * Creates a new axios instance for backend API calls with:
 * - Base URL pointing to game backend
 * - Authorization header from OAuth SDK
 * - Automatic token refresh on 401
 */
export function useGameAPI() {
  const { apiClient, getAccessToken } = useOAuth();
  
  // Create a new axios instance specifically for game backend API
  // Don't reuse OAuth SDK's client to avoid interfering with its userinfo calls
  const gameAxios = axios.create({
    baseURL: import.meta.env.VITE_BACKEND_BASE_URL || '/api/v1',
    timeout: 30000,
    headers: {
      'Content-Type': 'application/json',
    },
  });
  
  // Request interceptor: Add authorization and client ID headers
  gameAxios.interceptors.request.use(
    async (config) => {
      const token = await getAccessToken();
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }
      
      // Add X-Client-Id header for backend auth middleware
      const clientId = import.meta.env.VITE_OAUTH_CLIENT_ID;
      if (clientId) {
        config.headers['X-Client-Id'] = clientId;
      }
      
      return config;
    },
    (error) => Promise.reject(error)
  );
  
  // Response interceptor: Handle 401 by refreshing token
  gameAxios.interceptors.response.use(
    (response) => response,
    async (error) => {
      const originalRequest = error.config;
      
      // If 401 and haven't retried yet
      if (error.response?.status === 401 && !originalRequest._retry) {
        originalRequest._retry = true;
        
        try {
          // Use OAuth SDK's refresh mechanism
          await apiClient.refreshAccessToken();
          
          // Retry with new token
          const newToken = await getAccessToken();
          if (newToken) {
            originalRequest.headers.Authorization = `Bearer ${newToken}`;
          }
          return gameAxios(originalRequest);
        } catch (refreshError) {
          // Refresh failed, let it propagate
          return Promise.reject(refreshError);
        }
      }
      
      return Promise.reject(error);
    }
  );
  
  return new GameAPI(gameAxios);
}

/**
 * Legacy: Singleton instance (for backward compatibility)
 * @deprecated Use useGameAPI() hook instead
 */
let legacyClient: GameAPI | null = null;

export function getApiClient(): GameAPI {
  if (!legacyClient) {
    // This won't work outside React context
    // Kept for backward compatibility during migration
    throw new Error(
      'getApiClient() is deprecated. Use useGameAPI() hook instead:\n' +
      'const api = useGameAPI();'
    );
  }
  return legacyClient;
}
